"""empty message

Revision ID: 03252193b346
Revises: 
Create Date: 2024-04-03 17:45:27.821939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03252193b346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=45), nullable=True),
    sa.Column('terrain', sa.String(length=45), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('vehicle_class', sa.String(length=45), nullable=True),
    sa.Column('manufacturer', sa.String(length=45), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=45), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('people',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=45), nullable=True),
    sa.Column('skin_color', sa.String(length=45), nullable=True),
    sa.Column('eye_color', sa.String(length=45), nullable=True),
    sa.Column('birth_year', sa.String(length=45), nullable=True),
    sa.Column('gender', sa.String(length=45), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homeworldId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworldId'], ['planets.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_uid', sa.Integer(), nullable=True),
    sa.Column('vehicles_uid', sa.Integer(), nullable=True),
    sa.Column('planets_uid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_uid'], ['people.uid'], ),
    sa.ForeignKeyConstraint(['planets_uid'], ['planets.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicles_uid'], ['vehicles.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_drive_vehicles',
    sa.Column('people_drive_vehicles_id', sa.Integer(), nullable=False),
    sa.Column('people_uid', sa.Integer(), nullable=True),
    sa.Column('Vehicles_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Vehicles_uid'], ['vehicles.uid'], ),
    sa.ForeignKeyConstraint(['people_uid'], ['people.uid'], ),
    sa.PrimaryKeyConstraint('people_drive_vehicles_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_drive_vehicles')
    op.drop_table('favorites')
    op.drop_table('people')
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('planets')
    # ### end Alembic commands ###
